export default {
    PICK_DISPLAY_NAME: 'PICK_DISPLAY_NAME',
    CONNECTED_TO_ROOM: 'CONNECTED_TO_ROOM',
    KICKED_FROM_ROOM: 'KICKED_FROM_ROOM',
    ROOM_CLOSED: 'ROOM_CLOSED',
    ROOM_INACTIVE: 'ROOM_INACTIVE',
}