const VOTING_PHASE = 'VOTING_PHASE';
const RESULTS_PHASE = 'RESULTS_PHASE';

const ABSTAIN_VALUE = 'ABSTAIN';

module.exports.VOTING_PHASE = VOTING_PHASE;
module.exports.RESULTS_PHASE = RESULTS_PHASE;
module.exports.ABSTAIN_VALUE = ABSTAIN_VALUE;
